# .github/copilot.yml
# GitHub Copilot configuration for this repository

# Restrict Copilot suggestions to specific languages
languages:
  - typescript
  - javascript
  - sql

# Exclude specific files or folders from Copilot suggestions
exclude:
  - node_modules/
  - dist/
  - .next/
  - prisma/migrations/

packageManager: pnpm

tools:
  - git bash

# Enable or disable Copilot for this repository
enabled: true


